version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install
          command: yarn install --pure-lockfile
      - run:
          name: 'ESLint'
          command: yarn eslint .

workflows:
  version: 2
  test:
    jobs:
      - lint
